#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root/with sudo"
  exit 1
fi

NAME=$1
PORT=$2
DEVICE=$3

CONFIG_DIR=/etc/camera-streamer.conf.d
CONTROL=/usr/local/bin/camera-streamer-control

## Name

if [ -z "$NAME" ]; then
  echo "Usage: $0 <name> <port> <device>"
  exit 1
fi

# make sure the name is unique
if [ -e "$CONFIG_DIR/usb-$NAME.conf" ]; then
  echo "Camera $NAME already exists"
  exit 1
fi

## Port

if [ -z "$PORT" ]; then
  port=8080
  while grep -qs "PORT=$port" $CONFIG_DIR/*.conf; do
    port=$((port+1))
  done
  PORT=$port
  echo "No port provided, automatically selected port $PORT"
  echo
fi

# make sure the port is available
if grep -qs "PORT=$PORT" $CONFIG_DIR/*.conf; then
  echo "Port $PORT is already used by another camera"
  exit 1
fi

## Device

if [ -z "$DEVICE" ]; then
  echo "Please make sure your USB camera is plugged in and select it below:"
  echo
  PS3="? "
  options=($(echo /dev/v4l/by-id/usb-*-video-index0)) # list all the USB v4l2 devices
  select opt in "${options[@]}"; do
    if [ -n "$opt" ]; then
      DEVICE=$opt
      break
    fi
    echo
  done
  echo
fi

# make sure the device exists
if [ ! -e "$DEVICE" ]; then
  echo "Device $DEVICE does not exist"
  exit 1
fi

cat > $CONFIG_DIR/usb-$NAME.conf <<EOF
### Options for USB based cameras

# The port on which the webcam server for the camera should listen on.
PORT=$PORT

# The path to the camera device.
DEVICE=$DEVICE

# The image format of the camera.
FORMAT=YUYV

# The resolution to set on the camera. Defaults to 1280x720.
WIDTH=1280
HEIGHT=720

# The framerate to set on the camera. Defaults to 15fps.
FRAMERATE=15

# Additional options.
OPTIONS=
EOF

$CONTROL restart $NAME

echo "USB camera $NAME added"
echo
echo "Port:               $PORT"
echo "Device:             $DEVICE"
echo "Configuration file: $CONFIG_DIR/usb-$NAME.conf"
