#!/bin/bash

ALL=$1

CONFIG_DIR=/etc/camera-streamer.conf.d

echo "Available USB camera devices:"
for path in /dev/v4l/by-id/usb-*-video-index0; do
    if [[ "$ALL" == "--all" ]]; then
        echo
        echo "=== $path ==="
        echo
        v4l2-ctl --device "$path" --all --list-formats --list-formats-ext
    else
        echo "  None available"
    fi
done


echo
echo "Available libcamera devices (* = in a config):"
if [ -e /usr/bin/libcamera-hello ]; then
    IFS=$'\n'
    LIST=$(/usr/bin/libcamera-hello --list-cameras | grep -v '^ ' | sed -e '1,2d')
    for d in $LIST; do
        inuse=' '
        device=$(echo $d | grep -o '/base/soc/[^)]*')
        if grep -qs "DEVICE=$device" $CONFIG_DIR/*.conf; then
            inuse='*'
        fi
        echo "  [$inuse] $d"
    done
    unset IFS
else
    echo "  None available"
fi
