#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root/with sudo"
  exit 1
fi

NAME=$1

CONFIG_DIR=/etc/camera-streamer.conf.d
CONTROL=/usr/bin/camera-streamer-control

if [ -z "$NAME" ]; then
  echo "Usage: $0 <name>"
  exit 1
fi

if [ ! -e "$CONFIG_DIR/usb-$NAME.conf" ]; then
  echo "Camera $NAME does not exist"
  exit 1
fi

$CONTROL stop $NAME

rm $CONFIG_DIR/usb-$NAME.conf
rm /run/systemd/system/camera-streamer-usb-$NAME.path || true
systemctl daemon-reload
